[tool.poetry]
name = "python3.10.9"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.10.9"
matplotlib = "^3.6.3"
scipy = "^1.10.0"
pycryptodome = "^3.16.0"
# angr = "^8.20.6"
mpmath = "^1.1.0"
ipdb = "^0.13.3"
pandas = "^1.5.2"
pyyaml = "^5.3.1"
# gmpy2 = "^2.0.8"
dpkt = "^1.9.3"
beautifulsoup4 = "^4.9.1"
# tslearn = "^0.4.1"
# ortools = "^8.0.8283"
geopy = "^2.1.5"
qrcode = "^6.1"
gmpy2 = "^2.0.8"
pkcs1 = "^0.9.6"
ecdsa = "^0.18.0"
fastecdsa = "^2.3.0"
uncompyle6 = "^3.7.4"
tqdm = "^4.56.0"
opencv-python = "^4.5.1"
opencv-contrib-python = "^4.5.1"
PyPDF2 = "^1.26.0"
# itsdangerous = "^1.1.0"
Flask = "^2.2.2"
qiskit = "^0.41.0"
randcrack = "^0.1.5"
selenium = "^3.141.0"
lxml = "^4.6.3"
oletools = "^0.56.1"
pylatexenc = "^2.10"
base65536 = "^0.1.1"
websock = "^1.0.4"
# ipywidgets = "^7.6.3"
# ibm-quantum-widgets = "^1.0.3"
# qiskit-nature = "^0.1.3"
# pyscf = "^1.7.6"
kubernetes = "^25.3.0"
mlflow = "^1.17.0"
# pyopenms = "^2.6.0"
biopython = "1.73"
# numba = "^0.53.1"
pykeepass = "^4.0.1"
setuptools-rust = "^0.12.1"
ptpython = "^3.0.19"
redis = "^3.5.3"
cryptography = "3.4.7"
polyglot = "^16.7.4"
PyICU = "^2.7.4"
pycld2 = "^0.41"
certifi = "^2021.5.30"
SoundFile = "^0.10.3"
Qulacs = "^0.3.0"
Flask-Cors = "^3.0.10"
optuna = "^3.1.0"
lightgbm = "^3.3.1"
blake3 = "^0.2.1"
connexion = "^2.9.0"
sibc = "^1.0.3"
# tensorflow = "^2.7.0"
# torch = "^1.7.1"
# torchvision = "^0.8.2"
# h5py = "3.1.0"
# scikit-image = "^0.17.2"
numpy = "^1.23.0"
# docker-compose = "^1.29.2"
scikit-learn = "^1.0.2"
py-solc-x = "^1.1.1"
# web3 = {extras = ["tester"], version = "^5.26.0"}
# web3 = "^5.31.3"
python-dotenv = "^0.19.2"
ptrlib = "^1.4.2"
Cython = "^0.29.28"
dnspython = "^2.2.0"
pyminizip = "^0.2.6"
request-boost = "^0.6"
pyocr = "^0.8.1"
pyttsx3 = "^2.90"
# angr = "^9.1.12332"
pwntools = "^4.9.0"
six = "^1.16.0"
PyJWT = "^2.3.0"
prometheus-api-client = "^0.5.0"
Flask-SQLAlchemy = "^2.5.1"
python-evtx = "^0.7.4"
SQLAlchemy-serializer = "^1.4.1"
Flask-Login = "^0.6.1"
Flask-Session = "^0.4.0"
pynvim = "^0.4.3"
pyshark = "^0.4.5"
torch = "^1.13.1"
stepic = "^0.5.0"
torchvision = "^0.14.1"
tensorflow = "^2.11.0"
timm = "^0.6.7"
psycopg2 = "^2.9.3"
pyarrow = "^9.0.0"
mmh3 = "^3.0.0"
z3-solver = "^4.12.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
